name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
  package:
    name: Package
    needs: build
    uses: ./.github/workflows/package.yml
  release:
    name: Release
    needs: package
    uses: ./.github/workflows/release.yml
    secrets: inherit